#!/bin/bash
# $Id$
#
# =============================================================================
# Global configuration for tabmove.sh, idxmove.sh, idxrebuild.sh and
# analobj.sh
# -----------------------------------------------------------------------------
#                                                              Itzchak Rehberg
#
# login information
user=sys
password="pyha#"
# Oracle SID
export ORACLE_SID=$1
# Prefix for the log file to write to. The parameters passed to the script will
# be used to make the output name somehow unique. So with PREFIX set to DEFAULT,
# an example file name has the syntax "tabmov-$1-$2-$3.spool" for the script
# tabmove.sh
# Valid values are:
#  OFF     -- no log file will be written
#  DEFAULT -- script name will be used as prefix
# all other values will be understand literally. Since we use SQL*Plus and
# its SPOOL facility, existing files will be overwritten without warning!
PREFIX=DEFAULT

# ====================================================[ analobj & tabreorg ]===
# restrictions: what are the minimal settings to display?
NUMROWS=1000
CHAINCNT=10
# estimate or compute statistics?
CALCSTAT=COMPUTE
# Log all analyze statements as well (1) or only results (0)?
LOGALL=0

# ==============================================================[ tabreorg ]===
# tablespace to temporarily store the tables for reorganization. This must
# be a permanent (not a temporary!) tablespace!! Don't use "SYSTEM" here ;-)
TR_TMP=TEMP
# which value to add to PCTUSED
TR_USEDINC=0
# which value to add to PCTFREE
TR_FREEINC=10
# min pct of chained rows a table must have to be re-organized
TR_CHAINPCT=7
