CREATE TABLESPACE ts_mig
DATAFILE '+DATA' SIZE 25G AUTOEXTEND ON NEXT 1G MAXSIZE 100G
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 32K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

ALTER USER schema_owner
 DEFAULT TABLESPACE ts_mig
 QUOTA UNLIMITED ON ts_mig;
